name = "Hyper"
uuid = "52c95252-7b3d-4bfe-b16c-8590bf86de22"
authors = ["Gabriel Wu <wuzihua@pku.edu.cn> and contributors"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
StringViews = "354b36f9-a18e-4713-926e-db85100087ba"
hyper_jll = "a61b6c3d-25e5-5e83-9f29-3d6b98db101c"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
