const HYPER_HTTP_VERSION_1_0 = Int32(10)
const HYPER_HTTP_VERSION_1_1 = Int32(11)
const HYPER_HTTP_VERSION_2 = Int32(20)
const HYPER_HTTP_VERSION_NONE = Int32(0)
const HYPER_IO_ERROR = UInt(0xFFFFFFFE)
const HYPER_IO_PENDING = UInt(0xFFFFFFFF)
const HYPER_ITER_BREAK = Int32(1)
const HYPER_ITER_CONTINUE = Int32(0)
const HYPER_POLL_ERROR = Int32(3)
const HYPER_POLL_PENDING = Int32(1)
const HYPER_POLL_READY = Int32(0)

export HYPER_HTTP_VERSION_1_0,
    HYPER_HTTP_VERSION_1_1,
    HYPER_HTTP_VERSION_2,
    HYPER_HTTP_VERSION_NONE,
    HYPER_IO_ERROR,
    HYPER_IO_PENDING,
    HYPER_ITER_BREAK,
    HYPER_ITER_CONTINUE,
    HYPER_POLL_ERROR,
    HYPER_POLL_PENDING,
    HYPER_POLL_READY
